### ISSUE TITLE
Odiglet is emitting too much info logs

### ISSUE THREAD

**Issue by vitorhugoro1** [odigos-io/odigos#1026]
**Describe the bug**
When you setup a fresh install of Odigos and make the full setup of your apps, when the Collector send some trace to save the Odiglet generate a log of this operation.

**To Reproduce**
1. See the logs on odiglet when has any services receiving traces. 

**Expected behavior**
Any option to control when or which log level we want to use, like the `-zap-log-level` on instrumentor or scheduler. 

**Screenshots**
![image](https://github.com/keyval-dev/odigos/assets/11232497/a08e62e5-57d0-4f9d-a027-188124cb1ca7)

**Comment by blumamir** [comment]
Thanks @vitorhugoro1 ,

Indeed its emitting a lot of logs. related issue to apply the fix in the source: https://github.com/open-telemetry/opentelemetry-go-instrumentation/issues/691
