### ISSUE TITLE
Report destinations errors and status in the odigos ui

### ISSUE THREAD

**Issue by blumamir** [odigos-io/odigos#1079]
Currently, users can add new destination and add configuration options for them.

If there is an issue with the configuration, for example if the endpoint is invalid, odigos auto-scaler component will log the error and will not show any indication in the UI.

This issue is to add indication for the destination. So if everything goes well, the destination should indicate it, and if there are errors, I want to have the error message so the user can fix it.

To do that, we will need:
1. Add `Status` to the destination CRD [here](https://github.com/keyval-dev/odigos/blob/0cae40107c7468243995abd26583500f28f55905/api/odigos/v1alpha1/destination_types.go#L35) which should include `Conditions` similar to the ones in [actions](https://github.com/keyval-dev/odigos/blob/0cae40107c7468243995abd26583500f28f55905/api/odigos/actions/v1alpha1/deleteattribute_types.go#L42).
2. For all destinations, return an error from the `ModifyConfig` function, and write the error to the destination CRD or indicate success if there is no error. This should be applied [here](https://github.com/keyval-dev/odigos/blob/0cae40107c7468243995abd26583500f28f55905/autoscaler/controllers/gateway/config/root.go#L37).

After this step, the user can see any status and error in the CRD. The next step after this is done would be to report this data in the `frontent` code so it is accessible to odigos UI.

**Comment by ankur0904** [comment]
@blumamir I am interested in working on this issue

**Comment by blumamir** [comment]
> @blumamir I am interested in working on this issue

Thanks @ankur0904 let me know how it goes and if you have any questions or need assistance
