### ISSUE TITLE
Missing full URL on tracing

### ISSUE THREAD

**Issue by dirtyren** [odigos-io/odigos#1278]
**Describe the bug**
Sending traces from a Go application to signozn.  Some traces show a empty full URL

**To Reproduce**
Just install and instrument the application.
Tested on Odigos 1.0.67

**Expected behavior**
The full url should be shown

**Screenshots**
![image](https://github.com/odigos-io/odigos/assets/1627055/f2fe532c-89b4-4a4d-9486-4b980c7ac407)

**Comment by RonFed** [comment]
This should be fixed in v1.0.70

**Comment by dirtyren** [comment]
@RonFed version v1.0.70 is showing the url full path.
