### ISSUE TITLE
Odigos install failed when installing using CLI

### ISSUE THREAD

**Issue by Rajpratik71** [odigos-io/odigos#1313]
**Describe the bug**

While installing "Odigos" using CLI, it failed with below error

```
Installing Odigos version v1.0.73 in namespace odigos-system ...
Creating namespace odigos-system                  ✔
Creating OdigosDeployment                         ✔
Creating OdigosConfig                             ✔
Creating OwnTelemetry Pipeline                    ✔
Creating DataCollection                           ✔
Creating Instrumentor                             ✔
Creating Scheduler                                ✔
Creating OdigletW0701 01:03:21.600928  301551 warnings.go:70] would violate PodSecurity "restricted:v1.24": host namespaces (hostNetwork=true, hostPID=true), privileged (container "odiglet" must not set securityContext.privileged=true), allowPrivilegeEscalation != false (container "odiglet" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "odiglet" must set securityContext.capabilities.drop=["ALL"]; container "odiglet" must not include "SYS_PTRACE" in securityContext.capabilities.add), restricted volume types (volumes "run-dir", "var-dir", "odigos", "kernel-debug" use restricted volume type "hostPath"), runAsNonRoot != true (pod or container "odiglet" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "odiglet" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
                                  ✔
Creating AutoScaler                               ✔
Creating UI                                       ✔
Waiting for Odigos pods to be ready ...           X
ERROR timed out waiting for the condition
```

**To Reproduce**

1. odigos  install

**Expected behavior**

Install should get success

**Screenshots**

![image](https://github.com/odigos-io/odigos/assets/12658912/cff23c1d-2aaf-44ee-a5b9-a8f92a1dc6b9)

![image](https://github.com/odigos-io/odigos/assets/12658912/7c02b063-876f-4d8b-87dd-e29169662163)

**Additional Context**

I am installing it on Openshift

Client Version: 4.14.27
Kustomize Version: v5.0.1
Server Version: 4.14.27
Kubernetes Version: v1.27.13+048520e

**Comment by edeNFed** [comment]
Hi @Rajpratik71 
It looks like you have PodSecurityPolicy enabled in your cluster, can you try install using `odigos install --psp`

**Comment by Rajpratik71** [comment]
still same issue 

![image](https://github.com/odigos-io/odigos/assets/12658912/d0b8829d-fdb4-467e-81a3-954fbef21f0d)

![image](https://github.com/odigos-io/odigos/assets/12658912/f904f0d2-e57c-4951-8108-bcdae8be9e2f)

**Comment by Rajpratik71** [comment]
looks like [helm based install of odigos on openshift ](https://github.com/odigos-io/odigos-charts?tab=readme-ov-file#install-odigos-in-openshift)is working fine.

**Comment by edeNFed** [comment]
Hi @Rajpratik71 sorry I didn't realize you are using openshift for installing on openshift with CLI you need to run: odigos install --openshift 

In the future we will enable this flag by default if the CLI detects an openshift cluster to make it more user friendly.
