### ISSUE TITLE
odigos install failed，

### ISSUE THREAD

**Issue by limboys** [odigos-io/odigos#1371]
**Describe the bug**
[root@k8s1201 grafana]# odigos install
Installing Odigos version v1.0.82 in namespace odigos-system ...
Unknown Kubernetes cluster detected, proceeding with installation
> Creating namespace odigos-system                ✔
> Creating OdigosDeployment                       ✔
> Creating OdigosConfig                           ✔
> Creating OwnTelemetry Pipeline                  ✔
> Creating DataCollection                         ✔
> Creating Instrumentor                           ✔
> Creating Scheduler                              ✔
> Creating Odiglet                                X
ERROR failed to create typed patch object: .spec.updateStrategy.rollingUpdate.maxSurge: field not declared in schema

**Desktop (please complete the following information):**
- k8s 1.20.04

**Comment by edeNFed** [comment]
Hi @limboys can you try on a newer version of Kubernetes? The minimum version we test on is v1.23 (which was end of life more than a year ago)

**Comment by limboys** [comment]
Okay, the docs need to add a release notes would be more friendly
