### ISSUE TITLE
Tempo destination is not working due to Parsing Error with Appended Port 4317

### ISSUE THREAD

**Issue by jlimai** [odigos-io/odigos#1545]
**Describe the bug**
When creating the Tempo destination `backend.ns.svc.cluster.local:8888/tempo/api/push` in Odigos, it incorrectly appends :4317 to the endpoint. This results in the endpoint being formatted as `backend.ns.svc.cluster.local:8888/tempo/api/push:4317`

**To Reproduce**
Open Odigos UI, add a Tempo destination.  Add application to source and wait for data to be sent to Tempo endpoint.  We got error from Odigos  Gateway

**Expected behavior**
Expected Odigos to honor the Tempo endpoint destination as configured.

**Additional context**
Odigos version: `1.0.107`
EKS version: `1.25`

The culprit seems to be in this section ot `tempo.go`
```		currentConfig.Exporters[tempoExporterName] = GenericMap{
			"endpoint": fmt.Sprintf("%s:4317", url),
			"tls": GenericMap{
				"insecure": true,
			},
```
It seems to be hardcoded to force `4317` port.  It TrimSuffix and then readded it back.

**Comment by alonkeyval** [comment]
@jlimai Thank you for reporting this issue and sharing the steps to reproduce it. We'll make sure to keep you updated on our progress and let you know once the fix is deployed.

We appreciate your patience and support in helping us improve Odigos!
