### ISSUE TITLE
Unable to recognize sql query

### ISSUE THREAD

**Issue by zijiwork** [odigos-io/odigos#1695]
Unable to recognize sql query
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/4b879544-6535-481e-ae63-79dc712c4e94">

**Comment by david336362** [comment]
@zijiwork Thank you for reaching out.

Please set the following ENV variable: `OTEL_GO_AUTO_INCLUDE_DB_STATEMENT` to collect the db.query.text.
We will also fix the span so it won't show the field when the ENV variable is not set.
