### ISSUE TITLE
The data displayed on the choose source screen is incorrect.

### ISSUE THREAD

**Issue by alonkeyval** [odigos-io/odigos#482]
The list of applications that appear on the source selection page defaults to the applications of the default namespace, the problem occurs when there is a namespace that starts with a lowercase letter "d" and is displayed first in the dropdown list.

**To Reproduce**
1. Make sure you have a namespace that starts with a lowercase d, If it doesn't exist, you can create one with the command: `kubectl create ns <name>` 
2. Go to Setup page
5. See error

**Expected behavior**
The apps listed should correspond to the information displayed in the dropdown menu.

**Screenshots**
<img width="840" alt="image" src="https://github.com/keyval-dev/odigos/assets/138359965/29c311a3-1951-455d-ac9f-60b9d173587a">

**Comment by saputkin** [comment]
Hi @alonkeyval,
let me take care of it :)
basically need to make sure we choose the default ns instead of the one at index 0.

**Comment by saputkin** [comment]
@alonkeyval  hi sorry, I’m on reserve duty (Israel), won’t be able to do it in the near future :(

**Comment by alonkeyval** [comment]
> @alonkeyval hi sorry, I’m on reserve duty (Israel), won’t be able to do it in the near future :(

@saputkin be safe 🙏

**Comment by Geen-19** [comment]
Is this error still there?

**Comment by rauno56** [comment]
@alonkeyval, I'm not able to repro it. Are you?

**Comment by rauno56** [comment]
Tested again and not able to repro.
