### ISSUE TITLE
use DockerImage from ENV variable

### ISSUE THREAD

**Issue by ashish0x02** [odigos-io/odigos#749]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

please update hardcoded image to use configurable image tags.
https://github.com/keyval-dev/odigos/blob/de3daf79e33f1f5ff8e5f97c3134aaeed01d6811/autoscaler/controllers/gateway/deployment.go#L24

**Describe alternatives you've considered**
it will become a blocker to  many orgs whose workload is 500+ nodes and which are using private ECR repo(it will throw Docker rate limit error)

**Additional context**

**Comment by ashish0x02** [comment]
is it kind of env variable which I need to pass as k8s ENV during run time?

**Comment by blumamir** [comment]
> is it kind of env variable which I need to pass as k8s ENV during run time?

You can set it when you run `odigos install`.
Reference: https://docs.odigos.io/cli/odigos_install#options
