### ISSUE TITLE
Log receivers should be from source namespace only

### ISSUE THREAD

**Issue by edwardwu** [odigos-io/odigos#882]
**Describe the bug**
When choose the source from e.g. default namespace,
the filelog receciver should be use /var/log/pods/default_\*/\*/\*.log instead of /var/log/pods/\*/\*/\*.log
    receivers:
      filelog:
        exclude:
        - /var/log/pods/kube-system_\*/\*/\*.log
        include:
        - /var/log/pods/default_\*/\*/\*.log
        include_file_name: false
        include_file_path: true

**To Reproduce**
1. install v1.0.17
2. select source from all pods from default namespace
3. select log destination to use loki 
4. I will see the logs from all namespaces

**Expected behavior**
the logs should be from default namespace only

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 22.04

**Comment by edwardwu** [comment]
the same issue on v1.0.19
manually updated
filelog receciver to use /var/log/pods/**default_**\*/\*/\*.log

**Comment by edeNFed** [comment]
Hi @edwardwu 
Thanks for reporting! this is indeed a known bug in the current implementation.
If you would like to open a PR to fix it, we will be happy to accept it.
As a general idea, I think the easiest way to solve this would be to write a new `processor` for the collector that filters the logs according to the selected namespaces. Happy to elaborate more.

**Comment by edwardwu** [comment]
Hi @edeNFed 
Thanks for the suggestion. I can try to write a new processor for the collector that  that filters the logs according to the selected namespaces. Could you provide additional insights or further elaboration on this matter?
I also like to have a Clickhouse gateway too.

**Comment by rauno56** [comment]
@edwardwu, I'm looking into making this a better experience.

Current solution is clearly sub-optimal so the first idea is to narrow down the sources to only ones that have a specific label in k8s. That closes the flood and makes it usable.

Second step in my mind would be to make it configurable in the UI or by some other means, but happy to hear your thoughts.

**Comment by rauno56** [comment]
There's now a PR open to fix the pressing issue: https://github.com/keyval-dev/odigos/pull/1080

After #1080 only instrumented apps are collected for logs.

**Comment by rauno56** [comment]
Fixed by #1080
