### ISSUE TITLE
Odigos UI is not working

### ISSUE THREAD

**Issue by anandmahurakar** [odigos-io/odigos#979]
**Describe the bug**
When I deployed Odigos into Kubernetes with helm charts (Latest Version) 0.2.40, There is no UI service files.

If anybody knows solution, please let me know

**Comment by blumamir** [comment]
Hi @anandmahurakar 

Thanks for reaching out. 
At the moment, running the UI is performed with [odigos CLI](https://docs.odigos.io/installation#installing-odigos-cli). You can see documentation [here](https://docs.odigos.io/cli/odigos_ui)

We had a UI image deployed into k8s in the past, but there were a few legging issues that we need to address. Please let us know if that works well for your needs.

**Comment by blumamir** [comment]
related: https://github.com/keyval-dev/odigos-charts/issues/3

**Comment by blumamir** [comment]
> I know that svg/oligos-ui is missing in odigos-system

Do you mean you are expecting the UI as a k8s deployment + k8s service? At the moment, the UI can be run with the CLI like so (in mac):

```sh
brew install keyval-dev/homebrew-odigos-cli/odigos
odigos ui
```

Let me know if it works.

**Comment by blumamir** [comment]
@dhruv0090 to install the cli in linux you can download the executable from [releases page](https://github.com/keyval-dev/odigos/releases) and copy it to your path.

We have a plan to publish the cli also as deb and rpm packages, hope I can get to it soon.

Please let me know here or in slack if it works and if you need further assistance. I can also jump on a call to help troubleshoot any issue
